[project]
site_name = "Typst in Production"
site_description = "Master delivering PDF with Typst, in production environments."
site_author = "Joseph Barbier"
copyright = """
Copyright &copy; 2026 Yellow Sunflower
"""
nav = [
  { "Home" = "index.md" },
  { "Typst crash course" = "typst-crash-course.md" },
  { "From languages" = [
    "from-languages/index.md",
    "from-languages/python.md",
    "from-languages/R.md",
    "from-languages/javascript.md",
    "from-languages/rust.md",
  ] },
  { "CI/CD" = [
    "continuous/index.md",
    "continuous/integration.md",
    "continuous/delivery.md",
  ] }
]

[project.theme]
language = "en"
features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.path",
  "navigation.tabs",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "navigation.prune",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
