[project]
site_name = "Typst in Production"
# repo_url = "https://github.com/y-sunflower/typst-in-production"
site_url = "https://typst-in-production.com/"
site_description = "Master delivering PDF with Typst, in production environments."
site_author = "Joseph Barbier"
copyright = """
Copyright &copy; 2026 Yellow Sunflower
"""
docs_dir = "src"
extra_css = ["stylesheets/extra.css"]
nav = [
  { "Intro" = "index.md" },
  { "Crash course" = "crash-course.md" },
  { "From languages" = [
    "from/index.md",
    "from/python.md",
    "from/R.md",
    "from/javascript.md",
    "from/rust.md",
  ] },
  { "Quarto" = ["quarto/index.md", "quarto/R.md", "quarto/python.md"] },
  { "CI/CD" = [
    "continuous/index.md",
    "continuous/integration.md",
    "continuous/delivery.md",
  ] },
  { "About" = "about.md" }
]

[project.theme]
language = "en"
features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.path",
  "navigation.tabs",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "navigation.prune",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.icon]
repo = "fontawesome/brands/github"
